### ISSUE TITLE
buildpack update

### ISSUE THREAD

**Issue by ZMaxim** [avishayhajbi/lecturus#10]
Avishay, please run this command:
heroku buildpack:set https://github.com/ddollar/heroku-buildpack-multi.git
After that, plase check that the change was made by running:
heroku buildpack

**Comment by avishayhajbi** [comment]
the server is running ! thanks GOD !

On Fri, May 1, 2015 at 9:21 PM, Max notifications@github.com wrote:

> Avishay, please run this command:
> heroku buildpack:set https://github.com/ddollar/heroku-buildpack-multi.git
> After that, plase check that the change was made by running:
> heroku buildpack
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/avishayhajbi/lecturus/issues/10.

## 

_Avishay Hajbi_
_WEB APPLICATION DEVELOPER_
_(_ http://aevok.com/avishay*)*

**Comment by avishayhajbi** [comment]
heroku buildpacks:set https://github.com/ddollar/heroku-buildpack-multi.git -a lecturus
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs -a lecturus
git push heroku master

DONE!!
