### ISSUE TITLE
problem while sendind an integer and it become to string

### ISSUE THREAD

**Issue by avishayhajbi** [avishayhajbi/lecturus#8]
after update a video all the integers become to string.

**Comment by avishayhajbi** [comment]
please insert those line below the url ajax call:

dataType : 'json',
data: JSON.stringify(videoJson),
contentType: "application/json",

i saw you are using courseId as a string maybe it become to int by the change.

@vandervidi

**Comment by vandervidi** [comment]
חג'בי אני מודה לך מקרב ליבי. כולי מתרגש

2015-04-03 15:21 GMT+03:00 avishay notifications@github.com:

> please insert those line below the url ajax call:
> 
> dataType : 'json',
> data: JSON.stringify(videoJson),
> contentType: "application/json",
> 
> @vandervidi https://github.com/vandervidi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/avishayhajbi/lecturus/issues/8#issuecomment-89270875.

## 

Best regards,
Vidran Abdovich

If you love music , check out my website.
www.NowImListeningTo.com

http://www.nowimlisteningto.com

**Comment by avishayhajbi** [comment]
מצחיק מאוד
